name: Draft My Story
favicon: null
layout_spectrum: 0.703804410295561
typography_spectrum: 0.5095027452334762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f1d2b5'
    - '#0e1728'
    - '#6d6e72'
    - '#abacae'
  brandStrength: 0.31575160729698837
  lightness: 0.11488103028386831
  saturation: 0.1598715358413756
  rhythmicContrast: 0.4215988586656749
purpose: []
